name: Restrict PR source branch

on:
  pull_request:
    branches:
      - master

jobs:
  restrict-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          echo "Source branch is ${{ github.head_ref }}"
          if [ "${{ github.head_ref }}" != "develop" ]; then
            echo "❌ Pull requests to master must come from develop branch only."
            exit 1
          fi